name: 002 pull request 的时候输出 Hello pull request

on:
  pull_request:
    branches: [main]

jobs:
  job-hello-world-1:
    runs-on: ubuntu-latest
    steps:
      - name: 步骤 1
        run: echo "Hello pull request 1"
      - name: 步骤 2
        run: echo "Hello pull request 2"
      - name: 步骤 3
        run: echo "Hello pull request 3"
  job-hello-world-2:
    runs-on: ubuntu-latest
    steps:
      - name: 步骤 1
        run: echo "Hello pull request 1"
      - name: 步骤 2
        run: echo "Hello pull request 2"
      - name: 步骤 3
        run: echo "Hello pull request 3"
